<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link rel="stylesheet" href="css/blueprint/screen.css" type="text/css" media="screen, projection">
		<link rel="stylesheet" href="css/blueprint/print.css" type="text/css" media="print"> 
		<!--[if lt IE 8]><link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
		<link rel="stylesheet" href="css/edmanage.css" type="text/css" media="screen, projection">
		<title>EDManage: Testing Unsubscribe</title>
	</head>
	<body>
		<div class="container">
			<div class="prepend-2 span-8 append-4 errorblock">
				<img src="images/logo.jpg" width="310" height="80" />
			</div>
			<div class="span-8 append-2 last errorblock">
				<!-- TMPL_IF NAME=SUCCESS -->
				<div class="notice">
					<p>Your Unsubscribe Test was successful.<br /> <!-- TMPL_VAR NAME=RCPT --> will be correctly unsubscribed in a Production Run.</p>
				</div>
				<!-- TMPL_ELSE -->
				<div class="error">
					<p>
						Your request to Unsubscribe '<!-- TMPL_VAR NAME=RCPT -->' failed. Please check that you clicked a link that was generated by 
						EmGauge and that a valid email address was passed for Unsubscription. (If you want to debug, the received digest and the 
						testdigest were <!-- TMPL_VAR NAME=DIGEST --> and <!-- TMPL_VAR NAME=TESTDIGEST --> respectively.
					</p>
					<p>Please copy the message above and mail it to <a href="mailto:guru@dygnos.com">this address.</a></p>
				</div>
				<!-- /TMPL_IF -->
			</div>
		</div>
	</body>
</html>
